### ISSUE TITLE
Allow more style configurations like padding/margin and background color

### ISSUE THREAD

**Issue by thiagomajesk** [Gruntfuggly/activitusbar#11]
Would be really great if we could configure some kind of padding/ margin so the activitus icons won't look cluttered among other extensions icons. A complementary configuration is allowing users to define the background color for the activitusbar alone.

**Comment by Gruntfuggly** [comment]
Unfortunately there is very little you can control with the styling of the buttons. I could add an option to add some spaces around the buttons which might be useful.

If you want to change the background colour of the activity bar, you can set

```
{
    "workbench.colorCustomizations": {
        "activityBar.background": "#00AA00"
    }
}
```
to make it green, for example.

See https://code.visualstudio.com/docs/getstarted/theme-color-reference

**Comment by Gruntfuggly** [comment]
Ah, no, sorry - you're completely out of luck there. You can't alter the appearance apart from the colours I'm afraid. The only options there are are whether it is left or right aligned and the priorirty within the bar.
