### ISSUE TITLE
Examples and guidelines for activitusbar.views

### ISSUE THREAD

**Issue by buchs** [Gruntfuggly/activitusbar#12]
Thanks for this extension. I am all in favor of minimizing space for graphic elements that just sit there and don't do anything. I think it is a great use of wasted space. I was hoping to be able to customize the commands that are on the menu. After looking at your source, I came up with this, which I believe this is a correct example and the extension default:

      "activitusbar.views": {
          "explorer": "file-text",
          "search": "search",
          "scm": "repo-forked",
          "debug": "bug",
         "extensions": "package"
      }

I tried to add:  *"terminal": "search",*, but that didn't work. I am unsure if terminal is a valid command, and being relatively new, I don't know where to find available commands. I know how to get the VS Code command line with completion, but the names have embedded spaces and capitalization. So, I don't know how to map what I want to a command name that I would use in setting activitusbar.views. Also, I am unsure of how to find the catalog of available icons. They don't seem to match *.icns files (with removal of ".icns") in the VS Code installation folder. I installed a few font extensions and I tried the names of the some of the png files (minus extension) that were installed in the extension folder.

**Comment by Gruntfuggly** [comment]
Hi - the extension isn't designed to run arbitrary commands - it's intended to open the views normally shown in the activity bar (on the left).

The icons are from github's https://octicons.github.com/ set.

It sounds like you just want to trigger vscode commands from the status bar - you should probably try this extension instead:
https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands

The easiest way to find out what commands are available is to go to the Keyboard Shortcuts page and click the `keybindings.json` link at the top of the page. This will then show all the commands currently bound to keys and the unbound commands underneath (commented out).
