### ISSUE TITLE
Position configuration

### ISSUE THREAD

**Issue by irvnriir** [Gruntfuggly/activitusbar#13]
Would be great to add ability to move the toolbar to "menubar", because the current position at bottom is bit too far and wastes time on reaching it (i know the "menubar" have the commands in "view" category, but putting them as open buttons would save time on clicking,
best would be to position the toolbar on top of the "side panel", but i don't know if its difficult)

**Comment by Gruntfuggly** [comment]
Do you mean at the top right? I'm not sure if it's possible, but I'll have a look...

**Comment by Ilias48rus** [comment]
@Gruntfuggly At top left in my setup ("{ on top of the "side panel" }" (where is no some already existing bar, its about adding new one to the main interface))

**Comment by Gruntfuggly** [comment]
If it requires adding a new bar then it's not possible I'm afraid. Vscode only allows limited customisation to the GUI. I was thinking of adding buttons to the top right toolbar, but that would require creating new svg icons - the activity bar is the only thing that supports octicons.

**Comment by Ilias48rus** [comment]
Well its open source Electron app, so "not possible" is not really applicable here :)

**Comment by Gruntfuggly** [comment]
activitusbar is a vscode extension - it's built on the API provided by vscode. Extensions have no access to the core application - it is the main difference between vscode and Atom. 

Please feel free to open an issue with vscode itself.

Alternatively, if it's that easy, you could fork the code and do it yourself?

**Comment by Ilias48rus** [comment]
@Gruntfuggly thanks for info, thats sad and weird, well, in this casae guess 1st level in menubar would be the best place ([.. help explorer search ..], if it can be edited with extension of course)
p.s. What could i say that would mean that its easy?

**Comment by Gruntfuggly** [comment]
It's definitely a different approach from Atom and vscode - I think Microsoft want to keep tighter control of the look and feel though.

I was just suggesting that you could have a go yourself - extensions for vscode are actually pretty easy to write. There's loads of documentation and a good community on slack (vscode-dev-community.slack.com) for help. You could fork activitusbar and try modifying it to get it to do what you want, or start from one of the tutorials. Contributing to vscode itself is a bit more tricky though - and I still think it would need a change to create a different toolbar. 😞

**Comment by Ilias48rus** [comment]
@Gruntfuggly i'm not so active with VS Code to look into it,
what about the "menubar"?, also maybe it could be possible to insert the actions as always visible listbox items in each sidebar's tree(explorer, SCM, ..). the trees (or at least some of them) should be modifiable according to "Favorites" extension.

**Comment by Gruntfuggly** [comment]
When you say menubar, do you mean adding buttons to the actual main menu? I don't think this is possible either - I think the only place that would get close to what you're after is the editor title menubar.

Have a look here for what's possible:
https://code.visualstudio.com/api/references/contribution-points

I think it might be possible to add them to all the tree views, but that would put a lot of buttons on each one without much control over positioning.

I'll have a go at putting them in the title bar and see what it comes out like...

**Comment by Ilias48rus** [comment]
as i saw somewhere in VS Code the "title menubar" named "menubar"

**Comment by Gruntfuggly** [comment]
I don't think I am ever going to get round to doing this and I don't think it really makes sense as part of this extension - this one is about recreating the buttons in the status bar, so putting them elsewhere would be a bit odd. It might be useful as a separate extension though.
