### ISSUE TITLE
Unable to add tasks

### ISSUE THREAD

**Issue by FatehAK** [Gruntfuggly/activitusbar#15]
I am unable to add tasks as you suggested in your readme. I tried doing this to run the build task -
"task.build": "tools" 
this code won't work and icon is not added to the status bar
"tasks.build": "tools"
this code also doesn't work but icon is added to the status bar

I think the problem is that VS code has updated the 'task' command to 'tasks'

**Comment by Gruntfuggly** [comment]
HI - are you still having issues with this? The name of the task must match the label in the task definition otherwise it won't create a button.

**Comment by Gruntfuggly** [comment]
Closing assuming this is no longer a problem.
