### ISSUE TITLE
Add button for settings

### ISSUE THREAD

**Issue by bcomnes** [Gruntfuggly/activitusbar#17]
Is it possible to add a button to open settings (the gear in the activity side bar)?

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version with support for a settings button.

The config format has been updated - it should automatically migrate it for you when you restart. Then add

```
{
    "name": "settings",
    "octicon": "gear"
}
```
or any other icon you want.

Please let me know if it works OK.

**Comment by bcomnes** [comment]
Very cool! 

Sorry but I don't understand the instructions.  Do you have an example config that adds the settings icon to the set of default icons? 

Is `activitusbar.views` an array?

**Comment by bcomnes** [comment]
Is it possible to put all the buttons in the activity bar into activitusbar automatically?

**Comment by bcomnes** [comment]
ok figured it out:

```json
"activitusbar.views": [
    {
      "name": "explorer",
      "octicon": "file-text"
    },
    {
      "name": "search",
      "octicon": "search"
    },
    {
      "name": "scm",
      "octicon": "repo-forked"
    },
    {
      "name": "debug",
      "octicon": "bug"
    },
    {
      "name": "extensions",
      "octicon": "package"
    },
    {
      "name": "settings",
      "octicon": "gear"
    }
  ]
```

**Comment by bcomnes** [comment]
We can close this issue, I'll open a new issue with the above concerns.
