### ISSUE TITLE
Customizing views is confusing

### ISSUE THREAD

**Issue by bcomnes** [Gruntfuggly/activitusbar#18]
Customizing views is unnecessarily confusing. Here are a few ideas to improve:

1. Add example config to the README.  

Is "activitusbar.views" an object? An array? An array of objects?  It requires to much probing to figure this out as a user.  Adding a full example would add a lot of clarity. 

```json
"activitusbar.views": [
    {
      "name": "explorer",
      "octicon": "file-text"
    },
    {
      "name": "search",
      "octicon": "search"
    },
    {
      "name": "scm",
      "octicon": "repo-forked"
    },
    {
      "name": "debug",
      "octicon": "bug"
    },
    {
      "name": "extensions",
      "octicon": "package"
    },
    {
      "name": "settings",
      "octicon": "gear"
    }
  ]
```

2. Extending views

It would be easier if I could extend the defaults, instead of having to read source code to back out how to add a single gear icon for settings.  

e.g.

```
"activitusbar.extendViews": [{
      "name": "settings",
      "octicon": "gear"
    }]
```

Would extend the default views. 

3. Copy exactly what the activity bar has so one doesn't have to manage their own views. 

This would be my most preferred solution, since I just want the little buttons and don't want to look after config.

**Comment by Gruntfuggly** [comment]
1. OK - I still use the old split settings view which shows the default. With the new non-split view you don't get to see the information that is provided, which is a shame. I'll add the details to the README.md too.

2. This would be possible, but makes it much more complicated. I'm not sure why you had to read the source code - I added details to the README.md?

3. I could have just added the settings to the default which would have worked for you, but everybody else would then have got a new button which they may not have wanted. As you were the first person to ask for it I felt it was better to make it an option.

You're correct though, as without the split screen settings view it's hard to know what to do, so I'll update the README.md.

**Comment by bcomnes** [comment]
I'm happy! Great plugin :) Thanks for the additions ✌️

**Comment by bcomnes** [comment]
> split screen settings view

Is that still available? I couldn't find it this afternoon.

**Comment by Gruntfuggly** [comment]
`"workbench.settings.useSplitJSON": true` :grin:

**Comment by bcomnes** [comment]
Cool! I wonder how that got turned off.

**Comment by Gruntfuggly** [comment]
I think it was turned off by default when the settings GUI was introduced. I know I had to turn it back on. Not sure why as it shows so much more information... 😕
