### ISSUE TITLE
Settings Icon Not Working

### ISSUE THREAD

**Issue by mfreeman-xtivia** [Gruntfuggly/activitusbar#19]
Per the README ...

{
    "name": "settings",
    "icon": "gear"
}

does not appear to work fully correctly. I have tried adding this to my  settings and I see the icon flash by briefly and disappear. The area on the activitus bar is functional at that point (i.e. clicking on the blank space where the icon did briefly appear will cause the settings view to appear) but the icon isnt there

I tried using multiple different icons and it seems to make no difference for the problem

**Comment by Gruntfuggly** [comment]
That sounds odd. Can you see if there is anything in the developer tools console?

Also - is it possible that you have settings defined in "user" and "workspace"?

**Comment by mfreeman-xtivia** [comment]
Just tried changing the icon multiple times while having the debug console running. Nothing in the console log at all

I am not using any workspace settings--only user settings

**Comment by Gruntfuggly** [comment]
Please could you attach your config from your `settings.json` so I can try it out.

**Comment by mfreeman-xtivia** [comment]
Windows 10. VSCode 1.37.0

{
    "activitusbar.toggleSidebar": true,
    "activitusbar.views": [
        {
            "name": "settings",
            "icon": "search"
        },
        {
            "name": "explorer",
            "octicon": "file-text"
        },
        {
            "name": "search",
            "octicon": "search"
        },
        {
            "name": "scm",
            "octicon": "repo-forked"
        },
        {
            "name": "extensions",
            "octicon": "package"
        },
        {
            "name": "extension.project-manager",
            "octicon": "code"
        },
    ],
    "workbench.startupEditor": "newUntitledFile",
    "workbench.colorTheme": "Visual Studio Dark",
    "editor.codeLens": false,
    "editor.lineNumbers": "off",
    "breadcrumbs.enabled": false,
    "editor.fontSize": 13.25,
    "editor.minimap.enabled": false,
    "editor.rulers": [
        120
    ],
    "editor.formatOnSave": true,
    "git.path": "C:\\Users\\mfreeman\\AppData\\Local\\Atlassian\\SourceTree\\git_local\\cmd\\git.exe",
    "git.ignoreMissingGitWarning": false,
    "workbench.tips.enabled": false,
    "workbench.tree.renderIndentGuides": "none",
    "window.zoomLevel": 0.25,
    "git.autofetch": true,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.drawBoldTextInBrightColors": false,
    "terminal.integrated.fontWeightBold": "normal",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe",
    "terminal.integrated.fontFamily": "Consolas",
    "terminal.integrated.fontSize": 13.25,
    "workbench.activityBar.visible": false,
    "workbench.iconTheme": "vscode-great-icons"
} 
```

**Comment by Gruntfuggly** [comment]
The README.md is wrong - it should show:
`"octicon": "gear"` not `"icon": "gear"`

I'll update it.

**Comment by mfreeman-xtivia** [comment]
That was indeed the problem. Works fine now--thanks

**Comment by mfreeman-xtivia** [comment]
FYI doco is still broken here ...

https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.activitusbar

**Comment by Gruntfuggly** [comment]
Thanks - I forgot to publish the fix!

**Comment by HubKing** [comment]
Is this addressing the lack of the "Manage" button? I mean, the activity bar has 6 buttons but this extension replicates only 5. The "Manage" (the one that looks like a gear) is missing.

![image](https://user-images.githubusercontent.com/10900489/82043933-6687a980-96e7-11ea-988a-f4e1b33cb0ff.png)

**Comment by Gruntfuggly** [comment]
The extension was originally written to just provide the 5 views as the manage button isn't a view.  The settings button was added as a feature request, so if you want it in the status bar, you can add is using:
```
{
"name": "settings",
}
```
It only opens the settings page though - it doesn't provide the manage menu, which unfortunately isn't possible.
