### ISSUE TITLE
Provide option that allows using the default icons

### ISSUE THREAD

**Issue by thiagomajesk** [Gruntfuggly/activitusbar#23]
Hi! Visual Studio Code updated it's activity bar icons some time ago, so I'd like to see if it's possible to provide an option that allows using the default icons instead.

**Comment by Gruntfuggly** [comment]
It should already work - change your config:
```
file-text -> files
repo-forked -> source-control
bug -> debug
package -> extensions
```
I've updated the defaults too, so if you haven't modified the configuration, just updating the extension should work.

**Comment by thiagomajesk** [comment]
@Gruntfuggly I can confirm that this is working by default after updating. Thanks for the attention 👍
