### ISSUE TITLE
Third party items that would normally appear on the activityBar do not appear on the Activitus bottom bar

### ISSUE THREAD

**Issue by wickedjargon** [Gruntfuggly/activitusbar#24]
This third-party item appears on the `activityBar` (circled at the bottom):

![Screenshot_2020-01-04_19-52-33](https://user-images.githubusercontent.com/11734208/71773531-8387c100-2f2c-11ea-949e-b48cb0f279bb.png)
(This is the `Dart: Flutter Outline` item included in the Dart package)

However, it does not appear on the Activitus bar:

![Screenshot_2020-01-04_20-01-14](https://user-images.githubusercontent.com/11734208/71773561-0b6dcb00-2f2d-11ea-8506-45aca47ba112.png)

is there anyway to fix this?

**Comment by Gruntfuggly** [comment]
You need to look in the package.json file of the extension to find the name of the container. It will be something like this:
```
    "contributes": {
        "viewsContainers": {
            "activitybar": [
                {
                    "id": "xxxxx",
```

In the configuration for activitus bar, add to
```
    "activitusbar.views": [
        {
            "name": "extensions.xxxxx",
            "octicon": "workflow"
        },
```
change `workflow` to any octicon icon you want.

**Comment by Gruntfuggly** [comment]
Did you manage to get this working?

**Comment by wickedjargon** [comment]
Yes. Thank you :)

**Comment by sdyalor** [comment]
Could you paste the final config, cant get it work :(

**Comment by sdyalor** [comment]
![image](https://user-images.githubusercontent.com/50224521/83202817-13155280-a10e-11ea-8cac-d09bd3178627.png)
This did
Flutter works ;3

**Comment by sdyalor** [comment]
```
{
      "name": "extension.flutter",
      "codicon": "squirrel"
    },
    {
      "name": "extension.test",
      "codicon": "squirrel"
    }
```
Also for test too

**Comment by ADTC** [comment]
**Can you automate this?** I think having to manually configure and reconfigure the list of icons is tedious. I'd like the extension to just copy whatever icons are enabled in the Activity Bar, and automatically update the copy whenever the icons change.

**Comment by Gruntfuggly** [comment]
Unfortunately there is no API available to extensions that exposes the contents of the activity bar. 🙁

**Comment by ADTC** [comment]
@Gruntfuggly Thanks for the reply. There's another extension called Customize UI which can modify the positioning and scaling of the original activity bar. I can think of two hack-like methods from the same idea:

1. Scale down the original activity bar to the size of the status bar (after making it horizontal), then move it into the status bar via DOM tree modification.
2. Read the DOM tree of the original activity bar, and recreate the same buttons on the status bar in the section you already have.

Hopefully you can tell if any of this is possible and viable long term. Thanks 😊

**Comment by Gruntfuggly** [comment]
Looking at what that extension does, wouldn't it just be easier to use it to move the activity bar to the bottom? You wouldn't even need this extension then. If you just want to make it so that the activity bar looks integrated with the status bar, you could raise a feature request with that extension instead.

The DOM isn't available to extensions and I don't really want to add a dependency on the Monkey Patch extension just for this.

**Comment by ADTC** [comment]
Very fair comment! I will see what I can do. I have indeed decided to use that extension instead of yours after testing both. Hope you understand.

**Comment by Gruntfuggly** [comment]
No problem - I'd be interested to see where you get to - the whole point of this extension was to basically move the activity bar and make it smaller in the first place, so if it works, it will be better!

**Comment by jagowm** [comment]
Hi, can you help me please, i cant add Postman extension to activitusbar, this is package.json
<img width="1212" alt="Captura de pantalla 2023-07-23 a la(s) 12 51 55" src="https://github.com/Gruntfuggly/activitusbar/assets/17258085/8478b65d-24f9-411c-a190-f29892afcbf3">

i have been trying whit:

```
{
            "name:": "extension.sidebar-panel",
            "codicon": "extensions-view-icon"
}

{
            "name:": "extension.Postman.sidebar-panel",
            "codicon": "extensions-view-icon"
}

{
            "name:": "Postman",
            "codicon": "extensions-view-icon"
}

{
            "name:": "postman-for-vscode.sidebar-panel",
            "codicon": "extensions-view-icon"
}
```

and not working, thanks in advance.

**Comment by Erik262** [comment]
@Gruntfuggly Wouldn't it be helpful to have a feature where we can give the path to any icon we want? Many third-party extensions like Postman, Docker, and Project-Manager have implemented their icons differently. Like here with postman.
