### ISSUE TITLE
Codicons not being displayed on MacOS Catalina

### ISSUE THREAD

**Issue by xvelasqu** [Gruntfuggly/activitusbar#26]
```
Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:05:00.654Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Darwin x64 19.0.0

Activitus Bar v0.0.23
```

I tried changing the 'codicons' values in settings but only the 'search' icon is being rendered.

![image](https://user-images.githubusercontent.com/3730793/72912882-924be180-3d3c-11ea-957f-ad43cd5c329e.png)

**Comment by Gruntfuggly** [comment]
Looks like you're on an old version of vscode. That version probably doesn't support them so you'll have to stick with octicons.

**Comment by xvelasqu** [comment]
You're absolutely correct. Looks like after upgrading to Catalina [this issue](https://github.com/Microsoft/vscode/issues/7426#issuecomment-425093469) was preventing VSCode from auto updating. 

Thank you for the fast response. Closing this issue.
