### ISSUE TITLE
Command name extension in status bar

### ISSUE THREAD

**Issue by SheepDomination** [Gruntfuggly/activitusbar#27]
I want to add another extension to the bottom status bar.  It mentions in the documentation to find the commands and use the portion after the last dot.  I've done just that but the extra icon is not seen in the status bar ?
Must it be a workbench view, can it begin with the last dot followed by *show* or *toggle* followed by the rest of the View Name ?

**Comment by Gruntfuggly** [comment]
The easiest thing to do is to look in the package.json for the extension you want. It should be in `.vscode/extensions/<extension author>.<extension name>.<version>/package.json`
Have a look at my answer to #24.

**Comment by SheepDomination** [comment]
In the `package.json` file must I use the result of *name* as there is no *id* name under *contributes* ?

**Comment by Gruntfuggly** [comment]
What is the extension you are trying to add?

**Comment by SheepDomination** [comment]
The extension is called, Dashboard.

**Comment by Gruntfuggly** [comment]
If you mean this one: 
https://marketplace.visualstudio.com/items?itemName=kruemelkatze.vscode-dashboard
then it doesn't have a view, so it can't work with activitus bar at the moment.

I'll add a way to add arbitrary commands to the  bar...

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which supports commands, so you can add:
```
{
   "name": "command.dashboard.open",
   "codicon": "dashboard"
}
```

**Comment by SheepDomination** [comment]
I don't see the dashboard icon, if I should; or even another debug icon in the status bar ? I added the following to my workspace settings; but no icon ?
```
    {
                "name": "command.dashboard.open",
                "codeicon": "dashboard"
     }
```

**Comment by Gruntfuggly** [comment]
What version of vscode are you running and what version of the extension do you have?

**Comment by SheepDomination** [comment]
Version 1.41.1 of Code.
![activitus_capture](https://user-images.githubusercontent.com/6827459/73759857-8ac40980-473a-11ea-95cd-57e844e5c1a1.jpg)

**Comment by Gruntfuggly** [comment]
You've got "codeicon" not "codicon". Sorry, my fauit - my example was wrong.

Try
```
    {
                "name": "command.dashboard.open",
                "codicon": "dashboard"
     }
```

**Comment by SheepDomination** [comment]
It shows in the status bar, but when I attempt to run it I get this error; `command dashboard.open not found` ?

**Comment by Gruntfuggly** [comment]
If you go to the Dashboard extension in the extensions view, then select "Contributions", do you see the following:
![image](https://user-images.githubusercontent.com/376658/73800909-46278500-47b1-11ea-901a-90f7f4ccffb7.png)

**Comment by SheepDomination** [comment]
I got it working :) It was a simple mistake :)

**Comment by Gruntfuggly** [comment]
You can't add a label at the moment, although it would be a fairly easy addition I think.
However, you can add a tooltip if you need to see what the button does - just add `"tooltip":"whatever"` alongside the `"name"` and `"codicon"`.

**Comment by SheepDomination** [comment]
It still shows `command.dashboard.open` even after adding `"tooltip:"dashboard"`.
```
 {
                "name": "command.dashboard.open",
                "tooltip": "Dashboard",
                "codicon": "window",
            }
```

**Comment by Gruntfuggly** [comment]
I've fixed the tooltips and added optional labels. Please try the latest version and let me know how you get on.
```
{ 
    "name": "command.dashboard.open",
    "tooltip": "Dashboard",
    "codicon": "window",
    "label": "Dashboard"
}
```

**Comment by SheepDomination** [comment]
That is perfect, thank you.

**Comment by lelequinter** [comment]
Hi @Gruntfuggly I tired to add ThunderClient extension in the activitus bar, and a folowed the steps in this conversation but it doesn't work, can you help me?

![image](https://user-images.githubusercontent.com/75708317/223854141-d11e6bd6-1dfc-4800-b9e0-d479b6e98628.png)

**Comment by Gruntfuggly** [comment]
Try
```json
        {
            "name": "thunder-client-sidebar",
            "tooltip": "Thunder Client",
            "codicon": "dashboard"
        }
```

**Comment by lelequinter** [comment]
> Try
> 
> ```json
>         {
>             "name": "thunder-client-sidebar",
>             "tooltip": "Thunder Client",
>             "codicon": "dashboard"
>         }
> ```

Thank You so much, and can you help me how can I set the Thunder Client icon in the "codicon" ?
or even better where can I read the documentation how to set de extension icon in the "codicon" key?

**Comment by Gruntfuggly** [comment]
You can't set the codicon to the Thunder Client icon - the best you can do is find something similar in the set:

https://microsoft.github.io/vscode-codicons/dist/codicon.html

How about "symbol-event" ?

**Comment by SheepDomination** [comment]
I wanted to update that keybindings are not working; I get the icon added to Activitusbar but the keybindings doesn't work, and there is no other default keybindings ?
