### ISSUE TITLE
Adding extension to Activitus ?

### ISSUE THREAD

**Issue by SheepDomination** [Gruntfuggly/activitusbar#30]
Like another extension which I requested to have added to Activitus, can the extension Project Manager extension be added as well using the same procedure ?

**Comment by Gruntfuggly** [comment]
If you can find the view name from package.json, then just add it to the configuration. It should work fine.

**Comment by Gruntfuggly** [comment]
```
        {
            "codicon": "project",
            "name": "extension.project-manager"
        }
```
