### ISSUE TITLE
Cannot see icons

### ISSUE THREAD

**Issue by pkail** [Gruntfuggly/activitusbar#31]
Activitusbar worked perfectly for many months.  Today, I cannot see the icons.
I can see the tooltips, but not the buttons.  If I press where the buttons would be they work: I just can't see them.
I uninstalled VSCode and Activitusbar; I deleted the AB directory and then reinstalled.  I updated the dependencies in the package.json file.

**Comment by Gruntfuggly** [comment]
I recently made a change so that the colours can be derived from the theme (which works better in debug mode for example).

Do you have any configuration settings defined for activitusbar? If so, can you try commenting them out and seeing if that makes it work. If so, can you post the settings so I can see what the problem is?

Sorry for the inconvenience - I hoped it wouldn't have any impact on existing users.

You could also revert back to a previous version if you need to (probably 0.0.26).

**Comment by pkail** [comment]
Thanks very much for your help.
There are no specific config files for AB as far as I can see.  However, there are settings in my VSCode settings.json which set the colour to white (in two places).  White is the colour I need to make them visible.  However, they're not visible with those settings.
When I edit out all the AB settings out the icons appear: they are white but very faint.  I'll try version 0.0.26.

Here are the settings I am commenting out::
/*   "activitusbar.activeColour": "white",
    "activitusbar.views": [
        {
            "name": "explorer",
            "octicon": "file-text"
        },
        {
            "name": "search",
            "octicon": "search"
        },
        {
            "name": "scm",
            "octicon": "repo-forked"
        },
        {
            "name": "debug",
            "octicon": "bug"
        },
        {
            "name": "extensions",
            "octicon": "package"
        },
        {
            "name": "settings",
            "octicon": "gear",
        },
        {
            "name": "extension.bookmarks",
            "octicon": "bookmark",
        },
        {
            "name": "extension.gitlens",
            "octicon": "git-branch",
        },
        {
            "name": "extension.project-manager",
            "octicon": "browser",
        },
        {
            "name": "extension.SQLToolsExplorer",
            "octicon": "database"
        }
    ], */
    // "activitusbar.inactiveColour": "white",

**Comment by Gruntfuggly** [comment]
Ah - I think I know what's going on - you're using named colours. Try using #ffffff instead of white. I didn't realise it even worked like that?

**Comment by pkail** [comment]
>>With the settings commented out, does the currently selected view become brighter when you click the buttons?
No it doesn't.  Instead, the background area around the buttons becomes slightly brighter, making them less visible.
![Screenshot from 2020-04-30 06-23-07](https://user-images.githubusercontent.com/32025933/80715503-49c66180-8aab-11ea-8874-f95a33e5860d.png)

>>Ah - I think I know what's going on - you're using named colours. Try using #ffffff instead of white. I didn't realise it even worked like that?
Yes, that works.  Thanks very much for your help!

**Comment by Gruntfuggly** [comment]
Latest version supports hex colours, theme colours and CSS/HTML colour names.

**Comment by pkail** [comment]
Thanks for all your work!

**Comment by Gruntfuggly** [comment]
You're welcome!
