### ISSUE TITLE
Exclude if extension is not enabled

### ISSUE THREAD

**Issue by DrKGD** [Gruntfuggly/activitusbar#32]
Is it possible to exclude an icon from appearing if the given extension is not enabled?
I really enjoy the customability of VSCode Workspaces, but I'd really prefer to prevent the icon from being there instead of having it doing nothing at all.

Also, is it possible to have an "empty, non-activable space" as an Icon?
`
        {
            "name":"",
            "codicon": "kebab-vertical"
        },
`
![immagine](https://user-images.githubusercontent.com/44092476/81850201-f696e900-9557-11ea-9c07-4d0849095ce2.png)

**Comment by Gruntfuggly** [comment]
I'm not sure if it is possible to detect if an extension is enabled or not. Have you tried putting alternative configurations in the workspace settings for each workspace? 

I'll add an option to include a gap of some sort.

**Comment by DrKGD** [comment]
> Have you tried putting alternative configurations in the workspace settings for each workspace?

It actually is a lever idea, did not think of it beforehand (d'oh!).
It indeed works, sorry for bothering you!

Would be cooler if it was possible to check for the availability of an extension, but I really do not know how to possibly do that (you know, one single config to edit and move around all the time...).

**Comment by Gruntfuggly** [comment]
No problem. I believe there is some functionality in the pipeline to determine which views have been moved into the activity bar - this might unlock this capability.

**Comment by DrKGD** [comment]
I was thinking, is there any primitive capabilities in JSON to "append to an array"? 
So, instead of replacing "activitusbar.views" everytime in every workspace we just append to it?

**Comment by Gruntfuggly** [comment]
There's nothing in JSON to do that, but I could add a flag to the extension to tell it to merge the settings from workspace into the user setting (which I think is possible). That way you could have a base set and then just additional sets where you need them.

**Comment by DrKGD** [comment]
Thank you very much for your attention and keep up the good work!
I will patiently wait for an update 👀.

**Comment by Gruntfuggly** [comment]
I've just uploaded a version which supports separators (use an empty {} in the view list, or specify an icon if you want) and also supports combining the settings - put your base set in user settings, and additional ones in workspace settings.

**Comment by Gruntfuggly** [comment]
Currently you can't add separators in the workspace settings when combining, but I'll fix that shortly.

**Comment by DrKGD** [comment]
Uhm, just pulled the new update, empty spaces do work as expected (thank you!), still having problems setting up the base-addtional settings.

As I understood should be easy as that in the base settings:
![immagine](https://user-images.githubusercontent.com/44092476/81863923-38318f00-956c-11ea-80ff-6b8d76a6cbc7.png)

And this for the workspace settings
![immagine](https://user-images.githubusercontent.com/44092476/81864011-513a4000-956c-11ea-882a-f2df2ebcc7f6.png)

**Comment by Gruntfuggly** [comment]
Ah sorry - I forgot to say that you need to enable `activitusbar.combineWorkspaceSettings` !

**Comment by DrKGD** [comment]
I see, it works as intended now!
![immagine](https://user-images.githubusercontent.com/44092476/81871211-a596ed00-9577-11ea-9b83-348153d8b037.png)

If you do not mind I can go ahead and close this thread.
