### ISSUE TITLE
Find in Folder doesn't switch active button to search

### ISSUE THREAD

**Issue by sharifzadesina** [Gruntfuggly/activitusbar#34]
To reproduce this:
Inside Explorer right-click on a folder and select "Find in Folder...", you will see that it will switch to the search pane, but activitusbar will still show the Explorer as the active pane.

**Comment by Gruntfuggly** [comment]
Yes, unfortunately there are a few ways you can change the view without there being any way for the extension to be notified. I requested an API a long time ago to be able to see which view is active, but it never came to anything.

**Comment by sharifzadesina** [comment]
@Gruntfuggly how they detect it in the original activity bar?

**Comment by Gruntfuggly** [comment]
The original activity bar is built into the application so it has access to everything - this extension only gets to use what is available in the API.
