### ISSUE TITLE
Upload to Open VSX

### ISSUE THREAD

**Issue by matejdro** [Gruntfuggly/activitusbar#36]
Open source builds of VS Code on some Linux distribution use Open VSX instead of VS marketplace to install extensions: https://bugs.archlinux.org/task/67780

Any chance you could upload this extension to Open VSX?

Thanks.

**Comment by jonescamilla** [comment]
I would also love to advocate for this project being published on [open-vsx.org](https://open-vsx.org/). The publishing process is documented in the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by Gruntfuggly** [comment]
Now published - sorry it took so long!

**Comment by jonescamilla** [comment]
Love it! Thank you! 🙏
