### ISSUE TITLE
[Feature] Ability to put icons in Title bar instead of in status bar

### ISSUE THREAD

**Issue by kmolerov** [Gruntfuggly/activitusbar#39]
It will be great, if there is an option to put icons not in the status bar, but in the window title bar. For example next to the menu items. Or at the rite side of title bar, near minimize/close buttons.
Sometimes users like to disable status bar, as it brings view noise without provading value.

**Comment by Gruntfuggly** [comment]
Hi - please see https://github.com/Gruntfuggly/activitusbar/issues/13

Unfortunately the way the status bar works is totally different to the menus. Only a small part of the extension would be used for the menus. 

A separate extension would probably be the best way to go for this, or even a feature request for VS Code itself - it would be nice if the activity bar could simply be moved to other places, and made horizontal.
