### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by ravenaxiom** [Gruntfuggly/activitusbar#40]
Really love the extension, thank-you so much for it. 

Was just wondering if it would be possible to support the Outline view (if it's been moved to a different panel from the Explorer one)? I've tried different variations of `workbench.actions.view.outline` but have been unable to get it to work. I guess this might be a bit more tricky/impossible as the Outline is part of the Explorer view by default?

**Comment by Gruntfuggly** [comment]
Try

```
        {
            "name": "command.outline.focus",
            "codicon": "list-tree"
        }
```

Not sure why it's done differently from the other views.

**Comment by ravenaxiom** [comment]
That works perfectly, thank-you so much!
