### ISSUE TITLE
Add an extension

### ISSUE THREAD

**Issue by Adipol** [Gruntfuggly/activitusbar#41]
I would like to add the extension https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2&ssr=false#qna. I add it as follows but it doesn't work

      "name": "vscode-mysql-client2",
      "codicon": "window",

I would like your help

**Comment by Gruntfuggly** [comment]
You need to use the view identifiers. From looking at the extensions's `package.json`, it looks like the identifiers are `github-cweijan-mysql` and `github-cweijan-nosql`.

So you would need something like:
```
"name": "extension.github-cweijan-mysql",
"codicon":"window"
```
or
```
"name": "extension.github-cweijan-nosql",
"codicon":"window"
```

For more information please see the "Configuration" section in the README.md (https://github.com/Gruntfuggly/activitusbar)
