### ISSUE TITLE
Extension breaks default keyboard shortcuts with custom views config

### ISSUE THREAD

**Issue by tribut** [Gruntfuggly/activitusbar#42]
Hey,

my reason for installing this extension was to have a single button that toggles the activity bar of vscode. I therefore use the following configuration:
~~~~
    "activitusbar.views": [
        {
            "codicon": "gripper",
            "name": "command.workbench.action.toggleActivityBarVisibility"
        }
    ]
~~~~
This works great, but when I press Ctrl-Shift-E I now get the error:
~~~~
command 'activitusbar.showExplorerView' not found.
~~~~
Of course I can disable all shipped shortcuts in my user config, but I would appreciate a proper fix.

Thanks!

**Comment by Gruntfuggly** [comment]
To be honest, I never use the keybindings. I doubt many people do, so I'll remove them.

**Comment by Gruntfuggly** [comment]
I can't seem to publish to the marketplace at the moment. Here's the .vsix if you want to try it.

[activitusbar-0.0.38.vsix.zip](https://github.com/Gruntfuggly/activitusbar/files/6013318/activitusbar-0.0.38.vsix.zip)
