### ISSUE TITLE
Possible to show # of files changed notification for source control icon?

### ISSUE THREAD

**Issue by parterburn** [Gruntfuggly/activitusbar#43]
![](https://user-images.githubusercontent.com/791889/116756971-59cc9600-a9ca-11eb-84dc-3c23bd156e7f.png)

A helpful bit of context in the sidebar view is seeing the # of files changed next to the source control icon, which doesn't exist for the activitusbar icon...is it technically possible to show something similar? If not the number, for spacing issues, even highlighting it a different color to show there are pending changes?

![](https://user-images.githubusercontent.com/791889/116756929-44f00280-a9ca-11eb-8b89-7ba674cd2ac8.png)

**Comment by Gruntfuggly** [comment]
Unfortunately I don't think there is any API to get the information. It could potentially do some command line stuff to get the number of modifications?

I'll try and add something.

**Comment by Gruntfuggly** [comment]
Please try the latest version. 🙂

**Comment by parterburn** [comment]
Speedy! That's perfect. Closing issue.

**Comment by Gruntfuggly** [comment]
Hi - I've had to disable this by default - see #44. It makes no sense to me, but until I can reproduce it, it seems safer to make it "opt in".  You'll need to set
```
"activitusbar.showSourceControlCounter": true
```
