### ISSUE TITLE
Shorcut to load settings.json file rather than Settings page

### ISSUE THREAD

**Issue by bprabhus** [Gruntfuggly/activitusbar#45]
Is it possible to redirect a button to the open setings.json file in the editor rather than the settings page?

My current Activitus bar setting - 
```    
       {
            "name": "settings",
            "codicon": "gear",
        },
```

**Comment by Gruntfuggly** [comment]
Yes, you can use
```
        {
            "name": "command.workbench.action.openSettings",
            "codicon": "gear"
        }
```

**Comment by Gruntfuggly** [comment]
I should probably make that the default now.

**Comment by Gruntfuggly** [comment]
Ah wait - you mean the other way round!

**Comment by bprabhus** [comment]
Perfect! That works. 
Thanks
