### ISSUE TITLE
Not all icons are added to activitus

### ISSUE THREAD

**Issue by tbrodbeck** [Gruntfuggly/activitusbar#52]
Hey. I am not sure, if this issue was already addressed somewhere else:

I would like Activitus to exactly mirror the icons I have in my activity bar. That means, when I install a certain extension (for example Live Share) it is added to the activity bar automatically. But it seems it does not update Activitus.

So specifically, my activity bar shows 11 icons:
<img width="55" alt="Screen Shot 2022-01-23 at 15 27 05" src="https://user-images.githubusercontent.com/24418160/150683289-2292864a-9320-4b4f-afb2-797ca6b60ad6.png">

But Activitus shows only the default 5:
<img width="152" alt="Screen Shot 2022-01-23 at 15 27 31" src="https://user-images.githubusercontent.com/24418160/150683302-484c478e-b4a7-4d68-b2c3-140247f3fb54.png">

So why is there this mismatch? And how to sync them both?

**Comment by Gruntfuggly** [comment]
Unfortunately you'll have to set your activitus bar configuration manually - there's no way to know what extensions you have installed using the API. On top of that, the icons used in the activity bar are not available in the status bar - only codicons/octicons. The extension was never meant to fully recreate the activity bar - it's too difficult.

**Comment by tbrodbeck** [comment]
Thanks for clarifying that. A bummer that the api cannot do this. 
Cheers!
