### ISSUE TITLE
Allow for user to use settings to configure location of buttons

### ISSUE THREAD

**Issue by pmeaney** [Gruntfuggly/activitusbar#54]
First, thanks a ton for this extension, I love how much space it saves.
That said, it would be a bit more convenient (in my opinion) if the icon were in more of an upper-left location.

In general, it would be great to be able to configure location of buttons-- to have a few options for locations.
The default location would be the lower-left corner, as currently is the case.

However, it would be great to have at least two other placement locations, such as: Just below "Explorer" in upper left.  Or if it's possible, even in the top level bar of the application (I don't know if this is possible, but it would be great).

See attached image for a poorly done drawing of the idea.

Orange = idea 1 for placement location option (just below "Explorer")
Green = idea 2  for placement location option (in the top level bar of the application)

![idea for moving icons](https://user-images.githubusercontent.com/6299810/158456942-e906c58f-af87-4931-8f81-c3f768dc88dd.jpg)

**Comment by Gruntfuggly** [comment]
Hi - unfortunately it's only the status bar that can provide the same functionality. To add buttons to other places would require custom packages, which is outside the scope of the extension. The VSCode extension API is actually quite limited in respect of this sort of thing.

**Comment by pmeaney** [comment]
Ahh gotcha.  Thanks a ton for the quick response!! No prob!

**Comment by Gruntfuggly** [comment]
No problem - sorry I can't add the feature!

**Comment by cptSwing** [comment]
(butting in here to drop some props: while vscode ui editing seems very limited, your activitus bar extension made a world of difference to me already. one of my most-used extensions!)

**Comment by Gruntfuggly** [comment]
Thanks!
