### ISSUE TITLE
I dont get the name of de docker extension view

### ISSUE THREAD

**Issue by edofritz** [Gruntfuggly/activitusbar#61]
Whats its the name of the docker extension view to add on settings?

**Comment by jroman-sh** [comment]
extension.dockerView but I'm missing the name of the codicon, anyone knows?

**Comment by edofritz** [comment]
> extension.dockerView but I'm missing the name of the codicon, anyone knows?

Thanks, it works, regarding the icon, I just improvised

**Comment by alexanderadam** [comment]
So any recommendation for the icon?

[The official icon SVG seem to be called `docker.svg`](https://github.com/microsoft/vscode-docker/blob/main/resources/dark/docker.svg) but just using `docker` doesn't seem to work.
