### ISSUE TITLE
`CTRL+SHIFT+H` does not reveal / focus the replace field in the search panel

### ISSUE THREAD

**Issue by Kroc** [Gruntfuggly/activitusbar#8]
ActivitusBar adds a shortcut `CTRL+SHIFT+H` overriding the same built in command to show/focus the search pane in replace mode. VSCode normally reveals the replace field (if hidden) and focuses it. ActivitusBar is not doing this!

**Comment by Gruntfuggly** [comment]
Weird! Try the latest version - seems to work properly now.
Oddly, it was using 'workbench.action.replaceInFilesWithSelectedText' before, which didn't work. I've replaced it with 'workbench.action.replaceInFiles' which seems to work properly!?
