### ISSUE TITLE
The setting 'activitusbar.views' is invalid

### ISSUE THREAD

**Issue by Jonzzs** [Gruntfuggly/activitusbar#9]
I set the `activitusbar.views` to hide the `bug` view, but is no effect.

![](https://ws4.sinaimg.cn/large/006tNbRwgy1fuphpku94oj31kw10k7hz.jpg)

**Comment by Gruntfuggly** [comment]
Hi - unfortunately due to the way vscode aggregates the settings, you can't simply remove the setting like that. You have to use and empty string. Changing it to:
```
    "activitusbar.views": {
        "explorer": "file-text",
        "search": "search",
        "scm": "repo-forked",
        "debug": "",
        "extensions": "package"
    }
```
should do what you want. 8-)

**Comment by Jonzzs** [comment]
Thanks, it works.
